# Generated by Django 4.2 on 2023-04-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useretu',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
