# Generated by Django 4.2 on 2023-04-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useretu_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useretu',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
