# Generated by Django 4.2 on 2023-05-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useretu_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useretu',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
