# Generated by Django 4.2 on 2023-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useretu_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useretu',
            name='coin_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
