# Generated by Django 4.2 on 2023-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useretu_coin_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='useretu',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
