# Generated by Django 4.2 on 2023-05-17 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='subjects',
            field=models.ManyToManyField(related_name='semesters', to='schedule.subject', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mail',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_even', models.BooleanField(default=False, verbose_name='Четная неделя')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('time_start', models.TimeField(verbose_name='Начало лекции')),
                ('time_end', models.TimeField(verbose_name='Конец лекции')),
                ('day_of_week', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], max_length=64, verbose_name='День недели')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.subject')),
            ],
        ),
    ]
