# Generated by Django 4.2 on 2023-05-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_structure', '0005_alter_news_image'),
        ('schedule', '0002_semester_subjects_teacher_mail_teacher_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='university_structure.group'),
        ),
    ]
