# Generated by Django 4.2 on 2023-05-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='mail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(related_name='subjects', to='schedule.teacher', verbose_name='Преподаватель'),
        ),
    ]
