# Generated by Django 4.2 on 2023-05-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_rename_mail_teacher_email_remove_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(null=True, related_name='subjects', to='schedule.teacher', verbose_name='Преподаватель'),
        ),
    ]
