# Generated by Django 4.2 on 2023-05-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='schedule.teacher', verbose_name='Преподаватель'),
        ),
    ]
