# Generated by Django 4.2 on 2023-05-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_semester_subjects_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='schedule.subject', verbose_name='Предметы'),
        ),
    ]
