# Generated by Django 4.2 on 2023-05-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_structure', '0005_alter_news_image'),
        ('schedule', '0012_schedule_auditorium_schedule_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluateMethodSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_method', models.CharField(choices=[('0', 'Exam'), ('1', 'Offset')], default='0', max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.group')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_method', to='schedule.subject')),
            ],
        ),
    ]
