# Generated by Django 4.2 on 2023-05-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_structure', '0002_alter_group_department_alter_news_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='coin_reward',
            field=models.PositiveIntegerField(default=0, verbose_name='Награда за выполнение'),
        ),
    ]
