# Generated by Django 4.2 on 2023-05-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_structure', '0004_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
    ]
